name: CI

env:
  CARGO_TERM_COLOR: always
  MSRV: 1.56.0

on:
  push:
    # branches:
    # - main
    tags:
      - v*

jobs:
  check:
    name: Rust project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          components: rustfmt, clippy

      - name: Update rustup
        run: rustup self update


      - name: Install Rust
        run: |
          rustup set profile minimal
          rustup toolchain install nightly -c rust-docs
          rustup default nightly

      - name: Install mdbook
        run: |
          mkdir bin
          curl -sSL https://github.com/rust-lang/mdBook/releases/download/v0.4.5/mdbook-v0.4.5-x86_64-unknown-linux-gnu.tar.gz | tar -xz --directory=bin
          echo "$(pwd)/bin" >> $GITHUB_PATH

      - run: mkdir dist
      - run: git clone https://github.com/rust-lang-cn/rust-by-example-cn.git -b gh-pages dist/rust-by-example-cn --depth 1
      - run: git clone https://github.com/rust-lang-cn/book-cn.git -b gh-pages dist/book --depth 1
      - run: git clone https://github.com/rust-lang-cn/std-cn.git -b main std --depth 1
      - run: git clone https://github.com/rust-lang-cn/reference-cn.git -b master reference-cn --depth 1
      - run: git clone https://github.com/rust-lang-cn/rustdoc-cn.git -b master rustdoc-cn --depth 1
      # - run: git clone https://github.com/rust-lang-cn/edition-guide-cn.git -b master edition-guide-cn --depth 1
      - run: git clone https://github.com/zzy/rust-cookbook-zh-cn.git -b master rust-cookbook-cn --depth 1

      - run: cp -rp std/doc dist/std
      - run: rm -rf dist/book/.git
      - run: rm -rf dist/rust-by-example-cn/.git
      - run: rm -rf rustdoc-cn/.git
      - run: rm -rf reference-cn/.git
      - run: rm -rf rust-cookbook-cn/.git

      - name: reference-cn
        working-directory: reference-cn
        run: |
          mdbook build

      - name: rustdoc-cn
        working-directory: rustdoc-cn
        run: |
          mdbook build

      - name: rust-cookbook-cn
        working-directory: rust-cookbook-cn
        run: |
          mdbook build


      - run: |
          cp -rp reference-cn/book dist/reference
          cp -rp rustdoc-cn/book dist/rustdoc
          cp -rp rust-cookbook-cn/book dist/rust-cookbook
      
      - name: Create index.html
        working-directory: ./dist
        run: |
          cat > index.html << EOF
          <a href="book/" target="__blank"> book </a>
          <a href="reference/" target="__blank"> reference </a>
          <a href="rustdoc/" target="__blank"> rustdoc </a>
          <a href="rust-cookbook/" target="__blank"> rust-cookbook </a>
          <a href="std/std/" target="__blank"> std </a>
          <a href="rust-by-example-cn/" target="__blank"> rust-by-example-cn </a>
          EOF
      
      - name: Create README.md
        working-directory: ./dist
        run: |
          cat > README.md << EOF
          本仓库，将来自 [**@rust-lang-cn**](https://github.com/rust-lang-cn) 中 Rust 相关的中文文档仓库打包到 Docker 中，用于本地部署预览：

          - [Rust 标准库文档中文版](https://github.com/rust-lang-cn/std-cn)
          - [Rust 程序设计语言 中文版](https://github.com/rust-lang-cn/book-cn)
          - [Rust By Example 中文版](https://github.com/rust-lang-cn/rust-by-example-cn)
          - [Rust 参考手册中文版](https://github.com/rust-lang-cn/reference-cn)
          - [RustDoc 手册中文版](https://github.com/rust-lang-cn/rustdoc-cn)
          - [Rust Cookbook 中文版](https://github.com/rust-lang-cn/rust-cookbook-cn)

          ## Docker

          ```bash
          docker pull wcjiang/rust-cn-document-for-docker
          ```

          ```bash
          docker run --name rust-cn-document-for-docker -itd -p 9613:3000 wcjiang/rust-cn-document-for-docker:latest
          # Or
          docker run --name rust-cn-document-for-docker -itd -p 9613:3000 ghcr.io/jaywcjlove/rust-cn-document-for-docker:latest
          ```

          在浏览器中访问以下 URL

          http://localhost:9613/  
          http://localhost:9613/book/  
          http://localhost:9613/reference/  
          http://localhost:9613/rustdoc/  
          http://localhost:9613/rust-cookbook/  
          http://localhost:9613/std/std/  
          http://localhost:9613/rust-by-example-cn/  
          EOF

      - name: Deploy Website
        uses: peaceiris/actions-gh-pages@v3
        with:
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_message: ${{ github.event.head_commit.message }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist

      # Create Docker Image
      - name: Docker login
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build rust-cn-document-for-docker image
        run: docker image build -t rust-cn-document-for-docker .

      - name: Tags & Push image
        run: |
          # Strip git ref prefix from version
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          # Strip "v" prefix from tag name
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')

          echo "outputs.tag - $VERSION"
          docker tag rust-cn-document-for-docker ${{ secrets.DOCKER_USER }}/rust-cn-document-for-docker:$VERSION
          docker tag rust-cn-document-for-docker ${{ secrets.DOCKER_USER }}/rust-cn-document-for-docker:latest
          docker push ${{ secrets.DOCKER_USER }}/rust-cn-document-for-docker:$VERSION
          docker push ${{ secrets.DOCKER_USER }}/rust-cn-document-for-docker:latest

      # Create Docker Image in Github
      - name: Login to GitHub registry
        run: echo ${{ github.token }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build docker image
        run: docker build -t ghcr.io/jaywcjlove/rust-cn-document-for-docker:latest .

      - name: Publish to GitHub registry
        run: docker push ghcr.io/jaywcjlove/rust-cn-document-for-docker:latest

      - name: Tag docker image (beta) and publish to GitHub registry
        run: |
          # Strip git ref prefix from version
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          # Strip "v" prefix from tag name
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
          
          echo "version: v$VERSION"
          docker tag ghcr.io/jaywcjlove/rust-cn-document-for-docker:latest ghcr.io/jaywcjlove/rust-cn-document-for-docker:$VERSION
          docker push ghcr.io/jaywcjlove/rust-cn-document-for-docker:$VERSION